### ISSUE TITLE
Any reason why this isn't using ChatColor api?

### ISSUE THREAD

**Issue by eogra7** [Delta2Force/redditbrowser#2]
Any reason why this isn't using ChatColor api?

_Originally posted by @Arnuh in https://github.com/Delta2Force/redditbrowser/pull/1_

**Comment by delta2force** [comment]
When sending player messages, it actually is using the chatcolor api. In fact the only moment when it’s not used is with the armor stands which show the karma.

This is done because chatcolor does not work with armor stands.
