### ISSUE TITLE
Bigger images

### ISSUE THREAD

**Issue by DapperMickie** [Delta2Force/redditbrowser#5]
Would be nice to get better resolution pictures.

Can't we use something like  [this](https://stackoverflow.com/questions/25193738/split-an-image-into-parts/25193878) to split the image into a configurable amount of pieces?
Then create x blocks of images in the correct order to get the better resolution image
And ofc change the height/width/length of the floors depending on the configs

**Comment by ExcuseMi** [comment]
Yes, it's possible. 

![2019-07-27_05 45 36](https://user-images.githubusercontent.com/16978537/61989614-c9159900-b032-11e9-9686-f54642b4139a.png)

I'll probably create a pull request tomorrow for this.

**Comment by delta2force** [comment]
Fixed thanks to @ExcuseMi 's commit
